/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js type tooling. Keep it in source so
// TypeScript works before the first local dev run.
